import type { NextPage } from 'next'
import Head from 'next/head'
// Components
import Header from '../components/header'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* Header */}
      <Header />
      {/* Hero */}
      <div>
        <h1>Test</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Quia a quam mollitia deleniti blanditiis. At quod, magnam nemo cum officia dignissimos odit mollitia repellat voluptatem, temporibus ex vitae alias non.</p>
      </div>
      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}


    </div>
  )
}

export default Home
