import type { NextPage } from 'next'
import Head from 'next/head'
// Components
import Header from '../components/header'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* Header */}
      <Header />
      {/* Hero */}

      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}


    </div>
  )
}

export default Home
