import type { NextPage } from 'next'
import Head from 'next/head'
// Components
import Header from '../components/header'
import { FaBeer } from 'react-icons/fa';
import { BeakerIcon, AcademicCapIcon, AdjustmentsHorizontalIcon, AdjustmentsVerticalIcon, ArchiveBoxArrowDownIcon } from '@heroicons/react/24/outline'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* Header */}
      <Header />
      {/* Hero */}
      <div>
        <h1 className='text-h1 text-center'>Test</h1>
        <p className='text-center'>Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Quia a quam mollitia deleniti blanditiis. At quod, magnam nemo cum officia dignissimos odit mollitia repellat voluptatem, temporibus ex vitae alias non.</p>
        <div className='mt-10'>
          <AcademicCapIcon />
          <BeakerIcon />
          <AdjustmentsHorizontalIcon />
          <AdjustmentsVerticalIcon />

        </div>

      </div>
      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}


    </div>
  )
}

export default Home
